branch-defaults:
  default:
    environment: flask-env-prod
environment-defaults:
  flask-env-prod:
    branch: null
    repository: null
global:
  application_name: sesalta-prod
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
